application: datashopcare
version: 3
runtime: python27
api_version: 1
threadsafe: yes

# Handlers define how to route requests to your application.
handlers:
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /static/fonts/(.*\.ttf)
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.ttf)
  mime_type: application/x-font-ttf

- url: .*  # This regex directs all routes to main.app
  script: main.application

libraries:
- name: jinja2
  version: latest

- name: pycrypto
  version: "2.6"
